@abstract
class_name SteamIDs
extends Object

# Achievement API names
const ACH_HUNTER := &"ACH_HUNTER"
const ACH_FIRST_CRAFT := &"ACH_FIRST_CRAFT"
const ACH_MUSHROOM_STAFF := &"ACH_MUSHROOM_STAFF"
const ACH_ICE_STAFF := &"ACH_ICE_STAFF"
const ACH_SLIME_STAFF := &"ACH_SLIME_STAFF"
const ACH_TREASURE_HUNTER := &"ACH_TREASURE_HUNTER"
const ACH_CLOSE_CALL := &"ACH_CLOSE_CALL" # Hidden
const ACH_TAKE_A_BATH := &"ACH_TAKE_A_BATH" # Hidden
const ACH_SURVIVE_10_NIGHTS := &"ACH_SURVIVE_10_NIGHTS"
const ACH_LUMBERJACK := &"ACH_LUMBERJACK"
const ACH_BATTER_UP := &"ACH_BATTER_UP"
const ACH_HONEY_THIEF := &"ACH_HONEY_THIEF"
const ACH_SLAYER := &"ACH_SLAYER"
const ACH_SET_SAIL := &"ACH_SET_SAIL"
const ACH_DIAMOND_AGE := &"ACH_DIAMOND_AGE"
const ACH_CURSE_BROKEN := &"ACH_CURSE_BROKEN"

# Stat API names
const STAT_ENEMIES_KILLED := &"STAT_ENEMIES_KILLED"
const STAT_ITEMS_CRAFTED := &"STAT_ITEMS_CRAFTED"
const STAT_ISLANDS_EXPLORED := &"STAT_ISLANDS_EXPLORED"
const STAT_TREES_CHOPPED := &"STAT_TREES_CHOPPED"
const STAT_DEATHS := &"STAT_DEATHS"
const STAT_DAYS_SURVIVED := &"STAT_DAYS_SURVIVED"
