@abstract
class_name SteamIDs
extends Object

# Achievement API names
const ACH_FIRST_BLOOD := &"ACH_FIRST_BLOOD"
const ACH_HUNTER := &"ACH_HUNTER"
const ACH_FIRST_CRAFT := &"ACH_FIRST_CRAFT"
const ACH_CRAFT_MUSHROOM_STAFF := &"ACH_CRAFT_MUSHROOM_STAFF"
const ACH_FIRST_ISLAND := &"ACH_FIRST_ISLAND"
const ACH_TREASURE_HUNTER := &"ACH_TREASURE_HUNTER"
const ACH_CLOSE_CALL := &"ACH_CLOSE_CALL" # Hidden
const ACH_TAKE_A_BATH := &"ACH_TAKE_A_BATH" # Hidden

# Stat API names
const STAT_ENEMIES_KILLED := &"STAT_ENEMIES_KILLED"
const STAT_ITEMS_CRAFTED := &"STAT_ITEMS_CRAFTED"
const STAT_ISLANDS_EXPLORED := &"STAT_ISLANDS_EXPLORED"
const STAT_DEATHS := &"STAT_DEATHS"
